services:
  proxy_server:
    image: proxy_server
    container_name: proxy_server
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
    restart: always