worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    # stefanteubner.de
    server {
        listen 80;
        server_name stefanteubner.de www.stefanteubner.de home.stefanteubner.de mysports.stefanteubner.de mysportsapi.stefanteubner.de spreadcels.com spreadcels.de;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name stefanteubner.de www.stefanteubner.de;

        ssl_certificate /etc/letsencrypt/live/stefanteubner.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/stefanteubner.de/privkey.pem;

        location / {
            proxy_pass http://192.168.0.10:81;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    
    # home.stefanteubner.de

    server {
        listen 443 ssl;
        server_name home.stefanteubner.de;

        ssl_certificate /etc/letsencrypt/live/stefanteubner.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/stefanteubner.de/privkey.pem;

        location / {
            proxy_pass http://192.168.0.10:8581;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # mysports.stefanteubner.de

    server {
        listen 443 ssl;
        server_name mysports.stefanteubner.de;

        ssl_certificate /etc/letsencrypt/live/stefanteubner.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/stefanteubner.de/privkey.pem;

        location / {
            proxy_pass http://192.168.0.10:8100;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # mysports.stefanteubner.de

    server {
        listen 443 ssl;
        server_name mysportsapi.stefanteubner.de;

        ssl_certificate /etc/letsencrypt/live/stefanteubner.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/stefanteubner.de/privkey.pem;

        location / {
            proxy_pass http://192.168.0.10:4100;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # spreadcels

    server {

        listen 443 ssl;
        server_name spreadcels.com spreadcels.de;

        ssl_certificate /etc/letsencrypt/live/spreadcels.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/spreadcels.com/privkey.pem;

        location / {
	        proxy_pass http://192.168.0.10:3100;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    
}